# 1 Librerias

In [1]:
# Librerias de python necesarias para leer archivos, procesar y editar
import pandas as pd 
import numpy as np
from tqdm import tqdm
import pyreadstat

# 2 Cargar la data con los códigos

In [2]:
# cargamos los archivos identificando su ubicación 
df = pd.read_csv("tipology.csv")

In [3]:
df.head()

,P01,P02,id_hog,Numero_de_hijos,Numero_de_hijas,Parientes,No_Parientes,Codigo_Hogar,Codigo,lista_codigo,Tipology
0,1.0,1.0,10150001001010011,NaN,3.0,NaN,NaN,1.02.03.0,123,"['1', '2', '3']","['1', '2', '3']"
1,2.0,1.0,10150001001010021,1.0,NaN,NaN,NaN,1.03.0,13,"['1', '3']","['1', '3']"
2,2.0,1.0,10150001001010031,3.0,2.0,2.0,NaN,1.03.05.0,135,"['1', '3', '5']","['1', '3', '5']"
3,1.0,1.0,10150001001010041,2.0,3.0,1.0,1.0,1.02.03.05.08.0,12358,"['1', '2', '3', '5', '8']","['1', '2', '3', '5', '8']"
4,2.0,1.0,10150001001010051,NaN,NaN,NaN,NaN,1.0,1,['1'],['1']

# Seleccionar las columnas a utilizarse

In [4]:
df = df.rename(columns={'Numero_de_hijos':'Numero de hijos',
                        'Numero_de_hijas':'Numero de hijas',
                        'No_Parientes':'No Parientes',
                        'No_Parientes':'No Parientes',
                        'id_hog':'id'
                                                 })

In [5]:
# Seleccionar las columnas para el análisis
extrac_df =['P01', 'P02', 'id', 'Numero de hijos', 'Numero de hijas', 'Parientes', 'No Parientes',
         'Codigo']
df = df[extrac_df]

In [6]:
df.head()

,P01,P02,id,Numero de hijos,Numero de hijas,Parientes,No Parientes,Codigo
0,1.0,1.0,10150001001010011,NaN,3.0,NaN,NaN,123
1,2.0,1.0,10150001001010021,1.0,NaN,NaN,NaN,13
2,2.0,1.0,10150001001010031,3.0,2.0,2.0,NaN,135
3,1.0,1.0,10150001001010041,2.0,3.0,1.0,1.0,12358
4,2.0,1.0,10150001001010051,NaN,NaN,NaN,NaN,1

# Tratamiento de datos nulos

In [7]:
# Los nan no son iguales que los ceros

Change = ['Numero de hijos', 'Numero de hijas', 'Parientes', 'No Parientes']
for variable in Change:
    df[variable] = df[variable].fillna(0)

C:\Users\Dell\AppData\Local\Temp/ipykernel_11312/3075229303.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[variable] = df[variable].fillna(0)

In [8]:
df.head()

,P01,P02,id,Numero de hijos,Numero de hijas,Parientes,No Parientes,Codigo
0,1.0,1.0,10150001001010011,0.0,3.0,0.0,0.0,123
1,2.0,1.0,10150001001010021,1.0,0.0,0.0,0.0,13
2,2.0,1.0,10150001001010031,3.0,2.0,2.0,0.0,135
3,1.0,1.0,10150001001010041,2.0,3.0,1.0,1.0,12358
4,2.0,1.0,10150001001010051,0.0,0.0,0.0,0.0,1

In [9]:
df.shape[0]

3810548

In [11]:
df['Parientes'][2]

2.0

In [13]:
lista

['no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 3.0,
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 3.0,
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 3.0,
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 3.0,
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 3.0,
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 3.0,
 3.0,
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 3.0,
 3.0,
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 3.0,
 'no se cumple',
 'no se cumple',
 3.0,
 3.0,
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 3.0,
 3.0,
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 3.0,
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 3.0,
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 3.0,
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 'no se cumple',
 ...]

# Creación de variable Nh para el conteo total de hijos

In [8]:
# Creamos una columna usefull

df['Nh'] = df['Numero de hijos'] + df['Numero de hijas']

In [9]:
df.head()

,P01,P02,id,Numero de hijos,Numero de hijas,Parientes,No Parientes,Codigo,Nh
0,1.0,1.0,10150001001010011,0.0,3.0,0.0,0.0,123,3.0
1,2.0,1.0,10150001001010021,1.0,0.0,0.0,0.0,13,1.0
2,2.0,1.0,10150001001010031,3.0,2.0,2.0,0.0,135,5.0
3,1.0,1.0,10150001001010041,2.0,3.0,1.0,1.0,12358,5.0
4,2.0,1.0,10150001001010051,0.0,0.0,0.0,0.0,1,0.0

In [10]:
# Funcion
def check(a, b):
    for elemetlist in a:
        if elemetlist in b:
            return True
        return False

In [ ]:
123
str[1,2,3]
['1','2','3']

In [11]:
# Agregamos una columna para reemplazar valor

T = []

for i in tqdm(range(df.shape[0])):
    if check(['2'], list(str(df['Codigo'][i]))):
        if df['Nh'][i] != 0:
            if df['Parientes'][i] != 0:
                if df['No Parientes'][i] != 0:
                    T.append('16')
                else:
                    T.append('6')
            elif df['No Parientes'][i] != 0:
                T.append('10')
            else:
                T.append('2')
        elif df['Parientes'][i] != 0:
            if df['No Parientes'][i] != 0:
                T.append('16')
            else:
                T.append('7')
        elif df['No Parientes'][i] != 0:
            T.append('11')
        else:

            T.append('3')
    else:
        if df['Nh'][i] != 0:
            if df['Parientes'][i] != 0:
                if df['No Parientes'][i] != 0:
                    T.append('16')
                else:
                    if df['P01'][i] == 1.0:
                        T.append('8')
                    elif df['P01'][i] == 2.0:
                        T.append('9')
                    else:
                        T.append('nan')
            elif df['No Parientes'][i] != 0:
                if df['P01'][i] == 1.0:
                    T.append('12')
                elif df['P01'][i] == 2.0:
                    T.append('13')
                else:
                    T.append('nan')
            else:
                if df['P01'][i] == 1.0:
                    T.append('4')
                elif df['P01'][i] == 2.0:
                    T.append('5')
                else:
                    T.append('nan')
        elif df['Parientes'][i] != 0:
            if df['No Parientes'][i] != 0:
                T.append('16')
            else:
                T.append('14')
        elif df['No Parientes'][i] != 0:
            T.append('15')
        else:
            T.append('1')


# Agregar columna en la base de datos

df['Tipology'] = T

100%|█████████████████████████████████████████████████████████████████████| 3810548/3810548 [01:01<00:00, 62073.14it/s]

In [12]:
df

,P01,P02,id,Numero de hijos,Numero de hijas,Parientes,No Parientes,Codigo,Nh,Tipology
0,1.0,1.0,10150001001010011,0.0,3.0,0.0,0.0,123,3.0,2
1,2.0,1.0,10150001001010021,1.0,0.0,0.0,0.0,13,1.0,5
2,2.0,1.0,10150001001010031,3.0,2.0,2.0,0.0,135,5.0,9
3,1.0,1.0,10150001001010041,2.0,3.0,1.0,1.0,12358,5.0,16
4,2.0,1.0,10150001001010051,0.0,0.0,0.0,0.0,1,0.0,1
...,...,...,...,...,...,...,...,...,...,...
3810543,1.0,1.0,900451999022030021,0.0,0.0,0.0,0.0,1,0.0,1
3810544,1.0,1.0,900451999022030131,0.0,2.0,0.0,0.0,123,2.0,2
3810545,1.0,1.0,900451999022040011,1.0,2.0,0.0,0.0,123,3.0,2
3810546,1.0,1.0,900451999022040021,1.0,3.0,1.0,0.0,1237,4.0,6
3810547,1.0,1.0,900451999022040031,1.0,2.0,0.0,0.0,123,3.0,2

In [13]:
dic_tipologia = pd.read_excel('Diccionario tipologia de hogar.xlsx')

In [14]:
dic_tipologia

    Tipology                                 Tipo de Hogares
0          1                                     Unipersonal
1          2                    Nuclear Biparental con hijos
2          3                    Nuclear Biparental sin hijos
3          4     Nuclear Monoparental con jefatura masculina
4          5      Nuclear Monoparental con jefatura femenina
5          6                    Extenso Biparental con hijos
6          7                    Extenso Biparental sin hijos
7          8     Extenso Monoparental con jefatura masculina
8          9      Extenso Monoparental con jefatura femenina
9         10                  Compuesto Biparental con hijos
10        11                  Compuesto Biparental sin hijos
11        12   Compuesto Monoparental con jefatura masculina
12        13  Compuesto  Monoparental con jefatura  femenina
13        14                  Hogar no nuclear con parientes
14        15               Hogar no nuclear con no parientes
15        16                       Nuclear Extenso Compuesto

In [15]:
df['Tipology'] = df['Tipology'].astype('int64')
dic_tipologia['Tipology'] = dic_tipologia['Tipology'].astype('int64')

In [16]:
df = pd.merge(df, dic_tipologia, on= 'Tipology', how='outer' )

In [17]:
df

,P01,P02,id,Numero de hijos,Numero de hijas,Parientes,No Parientes,Codigo,Nh,Tipology,Tipo de Hogares
0,1.0,1.0,10150001001010011,0.0,3.0,0.0,0.0,123,3.0,2,Nuclear Biparental con hijos
1,1.0,1.0,10150001001010101,1.0,2.0,0.0,0.0,123,3.0,2,Nuclear Biparental con hijos
2,2.0,1.0,10150001001010121,0.0,1.0,0.0,0.0,123,1.0,2,Nuclear Biparental con hijos
3,1.0,1.0,10150001001010141,0.0,1.0,0.0,0.0,123,1.0,2,Nuclear Biparental con hijos
4,1.0,1.0,10150001001010191,1.0,1.0,0.0,0.0,123,2.0,2,Nuclear Biparental con hijos
...,...,...,...,...,...,...,...,...,...,...,...
3810543,1.0,1.0,900351999050010261,0.0,0.0,0.0,1.0,128,0.0,11,Compuesto Biparental sin hijos
3810544,1.0,1.0,900451901001070151,0.0,0.0,0.0,1.0,128,0.0,11,Compuesto Biparental sin hijos
3810545,1.0,1.0,900451999007020481,0.0,0.0,0.0,2.0,128,0.0,11,Compuesto Biparental sin hijos
3810546,1.0,1.0,900451999010010011,0.0,0.0,0.0,1.0,128,0.0,11,Compuesto Biparental sin hijos
3810547,1.0,1.0,900451999018030091,0.0,0.0,0.0,1.0,128,0.0,11,Compuesto Biparental sin hijos

In [18]:
df.to_csv('Tipologia_final.csv', index = False)

In [19]:
df = df.rename(columns={'Numero de hijos':'Numero_de_hijos',
                        'Numero de hijas':'Numero_de_hijas',
                        'No Parientes':'No_Parientes',
                        'No Parientes':'No_Parientes',
                        'id':'id_hog',
                        'Tipo de Hogares':'Tipo_de_Hogares'
                                                 })

In [20]:
#Guardar con libreria pyredstat
pyreadstat.write_sav(df, "df_tipology_final.sav")